name: test

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
        working-directory: ./demo
      - run: yarn build
        working-directory: ./demo
      - run: yarn serve -l 7357 build &
        working-directory: ./demo
      - run: yarn serve -l 8000 website &
        working-directory: ./demo
      - run: yarn test --headless --screenshots screenshots
        working-directory: ./demo
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: screenshots
          path: demo/screenshots
