name: test

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn build

  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demo
    steps:
      - uses: actions/checkout@v1
      - run: yarn && yarn build
        working-directory: ./
      - run: yarn
      - run: yarn build
      - run: yarn serve -l 7357 build &
      - run: yarn serve -l 8000 website &
      - run: mkdir screenshots
      - run: yarn test --headless --screenshots screenshots
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: screenshots
          path: demo/screenshots
